parameters:
- name: runTests
  type: string
  default: 'On'
- name: linuxImage

stages:

- stage: Data

  jobs:
  - job: Get_Data_Files
    displayName: Get Data Files
    condition: ne(${{ parameters.runTests }}, 'Off')

    variables: 
    - group: InternalKeys
    
    pool:
      vmImage: ${{ parameters.linuxImage }}
      
    steps:
    
    - bash: |
        wget "https://distributor.51degrees.com/api/v2/download?LicenseKeys=$(DeviceDetectionLicenseKey)&Type=21&Download=True&Product=23" -O "$(Build.SourcesDirectory)/51Degrees-Tac.zip"
      displayName: 'Download TAC V4 CSV data file'

    - task: Bash@3
      displayName: 'Extract TAC V4 CSV data file'
      inputs:
        targetType: 'inline'
        script: 'unzip -p $(Build.SourcesDirectory)/51Degrees-Tac.zip 51Degrees-Tac-All.csv > $(Build.SourcesDirectory)/51Degrees.csv'
        workingDirectory: '$(Build.SourcesDirectory)'

    - script: |    
          mv $(Build.SourcesDirectory)/51Degrees.csv $(Build.ArtifactStagingDirectory)/51Degrees.csv
      displayName: 'Move Data Files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'dataFiles'
        publishLocation: 'Container'